const $=s=>document.querySelector(s);let mode='url',lastReport='';
const tabs=[...document.querySelectorAll('.tab')];tabs.forEach(t=>t.onclick=()=>{mode=t.dataset.mode;tabs.forEach(x=>{x.classList.toggle('active',x===t);x.setAttribute('aria-selected',x===t?'true':'false')});$('#urlPanel').classList.toggle('hidden',mode!=='url');$('#htmlPanel').classList.toggle('hidden',mode!=='html')});
$('#auditForm').addEventListener('submit',async e=>{e.preventDefault();if(mode==='html'){const html=$('#htmlInput').value.trim();if(!html)return alert('Paste some HTML to analyze.');render(audit(html),'Pasted HTML')}else{const url=$('#urlInput').value.trim();if(!url)return alert('Enter a website URL.');try{new URL(url);const res=await fetch(url,{mode:'cors'});if(!res.ok)throw Error('HTTP '+res.status);render(audit(await res.text()),url)}catch(err){alert('This page cannot be read by the browser. Try pasting its HTML instead.\n\nReason: '+err.message)}}});
function audit(html){const d=new DOMParser().parseFromString(html,'text/html'), findings=[];const add=(severity,title,detail,fix)=>findings.push({severity,title,detail,fix});
if(!d.documentElement.lang)add('critical','Document language is missing','The root HTML element has no lang attribute.','Add a language such as <html lang="en">.');else add('pass','Document language is defined','The document declares a language.','Keep the lang value accurate for the page content.');
if(!d.title||!d.title.trim())add('warning','Page title is missing','A descriptive title helps users and assistive technologies identify the page.','Add a concise, unique <title>.');else add('pass','Page title is present','The document has a title.','Keep it descriptive and unique.');
const imgs=[...d.querySelectorAll('img')],badImgs=imgs.filter(x=>!x.hasAttribute('alt'));if(badImgs.length)add('critical',`${badImgs.length} image${badImgs.length>1?'s':''} missing alt text`,`Images without alt text may hide meaningful content from screen-reader users.`,`Add meaningful alt text, or alt="" for purely decorative images.`);else add('pass','Images have alt attributes',`${imgs.length} image${imgs.length!==1?'s':''} checked.`,'Verify that each alternative accurately represents its purpose.');
const links=[...d.querySelectorAll('a')],emptyLinks=links.filter(x=>!x.textContent.trim()&&!x.getAttribute('aria-label'));if(emptyLinks.length)add('warning',`${emptyLinks.length} link${emptyLinks.length>1?'s':''} have no accessible name`,'Links should communicate their destination or action.','Give the link descriptive text or an accessible label.');else add('pass','Links have accessible names',`${links.length} link${links.length!==1?'s':''} checked.`,'Avoid vague labels such as “click here”.');
const headings=[...d.querySelectorAll('h1,h2,h3,h4,h5,h6')],h1=headings.filter(x=>x.tagName==='H1');if(h1.length===0)add('warning','No H1 heading found','A clear main heading helps communicate page structure.','Add one descriptive H1 for the primary page topic.');else if(h1.length>1)add('warning',`${h1.length} H1 headings found`,'Multiple H1 elements can be valid in modern HTML, but they deserve review for a clear hierarchy.','Use headings to reflect the actual content structure.');else add('pass','Main heading found','One H1 heading is present.','Keep heading levels logical and descriptive.');
for(let i=1;i<headings.length;i++){const prev=+headings[i-1].tagName.slice(1),cur=+headings[i].tagName.slice(1);if(cur-prev>1){add('warning','Heading level skips detected',`A heading jumps from H${prev} to H${cur}.`,'Avoid skipping levels when possible; use a logical hierarchy.');break}}
const forms=[...d.querySelectorAll('input,select,textarea')].filter(x=>x.type!=='hidden'), unlabeled=forms.filter(x=>!x.labels?.length&&!x.getAttribute('aria-label')&&!x.getAttribute('aria-labelledby'));if(unlabeled.length)add('critical',`${unlabeled.length} form control${unlabeled.length>1?'s':''} lack a label`,'Form fields need programmatic labels so their purpose is clear.','Associate each control with a <label> or an appropriate ARIA label.');else add('pass','Form controls are labelled',`${forms.length} visible form control${forms.length!==1?'s':''} checked.`,'Confirm labels describe the expected input.');
const buttons=[...d.querySelectorAll('button')],emptyButtons=buttons.filter(x=>!x.textContent.trim()&&!x.getAttribute('aria-label'));if(emptyButtons.length)add('critical',`${emptyButtons.length} button${emptyButtons.length>1?'s':''} have no accessible name`,'Icon-only controls need an accessible name.','Add visible text or an aria-label.');
const landmarks=[...d.querySelectorAll('main,nav,header,footer,aside')];if(!d.querySelector('main'))add('warning','Main landmark is missing','A main landmark helps assistive-technology users jump to primary content.','Use <main> for the page’s primary content.');else add('pass','Main landmark found','The page contains a main landmark.','Keep primary content inside it.');
const contrastHints=[...d.querySelectorAll('[style*="color"],[style*="background"]')].length;if(contrastHints)add('warning','Color contrast needs manual review',`${contrastHints} element${contrastHints!==1?'s':''} use inline color/background styles.`,'Use a contrast analyzer and verify text against WCAG contrast requirements.');
if(!d.querySelector('meta[name="viewport"]'))add('warning','Viewport configuration is missing','Mobile browsers may not render the page as intended.','Add a responsive viewport meta tag.');
return {findings,stats:{images:imgs.length,links:links.length,forms:forms.length,headings:headings.length}}}
function render(report,source){const failures=report.findings.filter(x=>x.severity!=='pass').length,critical=report.findings.filter(x=>x.severity==='critical').length,score=Math.max(0,Math.round(100-failures*8-critical*7));$('#score').textContent=score;$('#resultTitle').textContent=score>=90?'Strong foundation':score>=70?'Some improvements needed':'Accessibility needs attention';$('#resultSummary').textContent=`${report.findings.filter(x=>x.severity==='pass').length} checks passed, ${failures} findings identified for ${source}.`;$('#stats').innerHTML=Object.entries(report.stats).map(([k,v])=>`<div class="stat"><b>${v}</b><span>${k}</span></div>`).join('');const filters=['all','critical','warning','pass'];$('#filterButtons').innerHTML=filters.map(x=>`<button class="filter ${x==='all'?'active':''}" data-filter="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('');const draw=f=>{$('#findings').innerHTML=report.findings.filter(x=>f==='all'||x.severity===f).map(x=>`<article class="finding"><div class="finding-top"><span class="badge ${x.severity}">${x.severity.toUpperCase()}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.detail)}</p><p><strong>Suggested fix:</strong> ${esc(x.fix)}</p></article>`).join('')};draw('all');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.filter)});lastReport=`AccessiCheck report for ${source}\nScore: ${score}/100\n\n`+report.findings.map(x=>`${x.severity.toUpperCase()}: ${x.title}\n${x.detail}\nFix: ${x.fix}`).join('\n\n');$('#results').classList.remove('hidden');$('#results').scrollIntoView({behavior:'smooth',block:'start'})}
$('#copyReport').onclick=async()=>{await navigator.clipboard.writeText(lastReport);$('#copyReport').textContent='Copied ✓';setTimeout(()=>$('#copyReport').textContent='Copy report',1500)};function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
